Description: IAM role AmazonSecurityLakeMetaStoreManager for Security Lake
Resources:
  AmazonSecurityLakeMetaStoreManagerIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'AmazonSecurityLakeMetaStoreManager'
      Description: 'IAM role for AWS Security Lake'
      # Trust relationships
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - securitylake.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      # Premissions
      Policies:
        # Security policy
        - PolicyName: AmazonSecurityLakeMetaStoreManager
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: 'AllowWriteLambdaInsights'
                Effect: Allow
                Action: 
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:log-group:/aws/lambda-insights:*'
              - Sid: 'AllowCreateCloudWatchLogGroup'
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                Resource: '*'
              - Sid: 'AllowCreateAwsCloudWatchLogGroup'
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                Resource: 'arn:aws:logs:*:*:*'
              - Sid: 'AllowWriteLambdaApplicationLogs'
                Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:log-group:/aws/lambda/*'
              - Sid: 'AllowGlueManage'
                Effect: Allow
                Action:
                  - 'glue:CreatePartition'
                  - 'glue:CreatePartitionIndex'
                  - 'glue:GetPartition'
                  - 'glue:GetPartitionIndexes'
                  - 'glue:GetPartitions'
                  - 'glue:UpdateTable'
                  - 'glue:GetTable'
                  - 'glue:GetDatabase'
                  - 'glue:CreateDatabase'
                  - 'glue:CreateTable'
                  - 'glue:GetTables'
                  - 'glue:BatchCreatePartition'
                Resource: 
                  - 'arn:aws:glue:*:*:table/amazon_security_lake_glue_db*/*'
                  - 'arn:aws:glue:*:*:database/amazon_security_lake_glue_db*'
                  - 'arn:aws:glue:*:*:catalog'
                  - 'arn:aws:glue:*:*:database/default'
              - Sid: 'AllowToReadFromSqs'
                Effect: Allow
                Action:
                  - 'sqs:ReceiveMessage'
                  - 'sqs:DeleteMessage'
                  - 'sqs:GetQueueAttributes'
                Resource: !Sub 'arn:aws:sqs:*:${AWS::AccountId}:*'
# Output ARN of role
Outputs:
  RoleARN:
    Description: IAM role ARN
    Value: !GetAtt AmazonSecurityLakeMetaStoreManagerIAMRole.Arn